### PR TITLE
docker: Mock plugin dockerfile

### PR DESCRIPTION
**Pull request by lpabon**
Signed-off-by: Luis Pabón <luis@portworx.com>

### CODE REVIEW

**Comment by lpabon** [comment]
FYI: The CLA could be something that interferes with the development.

**Comment by akutz** [comment]
Hi @lpabon,

I do not see the value in a Dockerfile that literally just performs a Go get. GoCSI has no unversioned Go dependencies or is reliant on native C code, so as long as Go is present, Mock is built as easy the Dockerfile's `go get` command.

**Comment by lpabon** [comment]
Hi @akutz ,
  I am trying to create a container which mocks CSI plugin calls. Since this project already has a mock plugin, I just needed to containerize it, then have Docker hub or Quay.io automatically create containers. 

A go get gets the sources, compiles them, and installs them in the $GOPATH/bin directory automatically.

**Comment by akutz** [comment]
Hi @lpabon,

A few things regarding this PR:

1. I disagree with its basic value, but that's my opinion, and I recognize this could hold value for some.
2. I understand what the `go get` does. That's why I said doing it outside the container is trivial.
3. I'd rather see this Dockerfile take the current sources and build them inside a container in order to make it related to the working sources or current commit.
4. Regardless of No. 3, I want to see the Dockerfile update to reflect a specific version of Golang, not `latest`. I prefer to keep versions static and update them when required. Thanks!

**Comment by akutz** [comment]
Hi Luis,

I️ don’t to block you, so if you’d just update the Go version on which the Dockerfile is based I’ll merge as is. We can update it later to build from the current source. Thanks!

**Comment by lpabon** [comment]
No longer need this, thank you.

**Comment by akutz** [comment]
Hi Luis,

Okay, sorry for that. Please let me know if anything else you might need. FYI, did you see I took your suggestion regarding CSC?

**Pull request closed without merging**
